package com.example.kinit.e_medicalrecord.Enum;

public enum Medical_Transaction {
    LAB_RESULT,
    MEDICAL_PRESCRIPTION,
    FAMILY_HISTORY, UPDATE_FAMILY_HISTORY,
    SURGICAL_HISTORY, UPDATE_SURGICAL_HISTORY, INSERT_SURGICAL_HISTORY,
    PAST_MEDICAL_HISTORY, UPDATE_PAST_MEDICAL_HISTORY,
    SOCIAL_HISTORY, UPDATE_SOCIAL_HISTORY
}
